"""Third-party models and datasets gyeol can use: name, license, source, download URL and checksum.

This is documentation, not enforcement.  ``gyeol fetch <name>`` downloads an asset that has a URL and verifies its
SHA-256; checkpoints and model cards record which listed assets they were built from (:func:`describe`).  Complying
with each license, and with applicable law, is the responsibility of whoever uses the asset.

The license strings are as listed upstream at the time of writing; check the source before relying on them.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

DATASET, WEIGHTS, CODE = "dataset", "weights", "code"


@dataclass(frozen=True)
class Asset:
    name: str
    kind: str  # "dataset" | "weights" | "code"
    license: str
    source: str  # project page / citation
    url: str | None = None  # direct download used by ``gyeol fetch``; None = obtain manually from ``source``
    sha256: str | None = None  # verified by ``gyeol fetch`` and by loaders that read the file
    notes: tuple[str, ...] = ()


_AIHUB = ("AI Hub terms: commercial use of trained models with attribution to AI Hub (NIA); no redistribution of raw data; "
          "raw data processed in Korea; each user downloads the data under their own account.",)

ASSETS: dict[str, Asset] = {
    a.name: a
    for a in [
        # datasets
        Asset("vocalset", DATASET, "CC-BY-4.0", "VocalSet (Wilkins et al., ISMIR 2018)"),
        Asset("gtsinger", DATASET, "CC-BY-NC-SA-4.0", "GTSinger (NeurIPS 2024 Datasets and Benchmarks)"),
        Asset("popbutfy", DATASET, "CC-BY-NC-SA", "PopBuTFy"),
        Asset("csd", DATASET, "CC-BY-NC-SA-4.0", "CSD — https://github.com/equal-singer/CSD"),
        Asset("opencpop", DATASET, "CC-BY-NC", "Opencpop"),
        Asset("vocalcoachbench", DATASET, "mixed per source (Smule Research Data License, CC-BY-NC-SA-4.0, CC-BY(-SA)-4.0)",
              "VocalCoachBench (arXiv:2609.04241)", notes=("Audio keeps each source corpus's license; the annotation license is not stated.",)),
        Asset("aihub_473_guide_vocal", DATASET, "AI Hub terms", "https://aihub.or.kr (다음색 가이드보컬 #473)", notes=_AIHUB),
        Asset("aihub_465_multi_singer", DATASET, "AI Hub terms", "https://aihub.or.kr (다화자 가창 #465)", notes=_AIHUB),
        Asset("vocadito", DATASET, "CC-BY-4.0", "vocadito (Bittner et al., 2021)",
              notes=("Human-annotated f0; used for pitch evaluation.",)),
        Asset("mir1k", DATASET, "not stated in the distribution", "MIR-1K (Hsu & Jang, 2010)",
              notes=("Human-annotated pitch; used for pitch evaluation.",)),
        Asset("gyeol_synthetic", DATASET, "generated by gyeol (no recordings)", "gyeol.synth / gyeol.data.prepare"),
        Asset("own_recordings", DATASET, "your own recordings", "recordings made with your application"),
        # weights
        Asset("bigvgan_v2", WEIGHTS, "MIT", "NVIDIA BigVGAN"),
        Asset("vocos", WEIGHTS, "MIT", "Vocos"),
        Asset("dac", WEIGHTS, "MIT", "Descript Audio Codec"),
        Asset("hubert_fairseq", WEIGHTS, "MIT", "fairseq HuBERT"),
        Asset("contentvec", WEIGHTS, "MIT", "ContentVec"),
        Asset("rmvpe", WEIGHTS, "Apache-2.0", "RMVPE (Wei et al., Interspeech 2023)"),
        Asset("fcpe", WEIGHTS, "MIT", "torchfcpe"),
        Asset("swiftf0", WEIGHTS, "MIT", "SwiftF0"),
        Asset("roformer_community", WEIGHTS, "MIT (as listed)", "community Mel/BS-RoFormer weights",
              notes=("Training-data provenance of the community weights is not documented.",)),
        Asset("bs_roformer_viperx_ep317", WEIGHTS, "not stated upstream (listed with community RoFormer weights as MIT)",
              "viperx BS-RoFormer vocal model (model_bs_roformer_ep_317_sdr_12.9755; UVR public model repository); "
              "architecture: gyeol.frontend.roformer.BSRoFormer with VIPERX_EP317",
              url="https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/model_bs_roformer_ep_317_sdr_12.9755.ckpt",
              sha256="5b84f37e8d444c8cb30c79d77f613a41c05868ff9c9ac6c7049c00aefae115aa",
              notes=("Checksum of the file served at the URL on 2026-10-01 (639,331,213 bytes).",
                     "Training-data provenance is not documented.")),
        Asset("openvpi_nsf_hifigan", WEIGHTS, "CC-BY-NC-SA-4.0", "openvpi vocoders (pretrained weights)"),
        Asset("openvpi_pc_nsf_hifigan", WEIGHTS, "CC-BY-NC-SA-4.0", "openvpi vocoders (pretrained weights)"),
        # code gyeol does not include (reimplemented or optional)
        Asset("so_vits_svc", CODE, "AGPL-3.0", "so-vits-svc", notes=("Not included in or required by gyeol.",)),
        Asset("pesto", CODE, "LGPL-3.0", "PESTO", notes=("Not included in or required by gyeol.",)),
    ]
}


def asset(name: str) -> Asset:
    """The listed asset ``name`` (``KeyError`` with the known names if it is not listed)."""
    try:
        return ASSETS[name]
    except KeyError:
        raise KeyError(f"{name!r} is not in gyeol's asset list (known: {', '.join(sorted(ASSETS))}); add it with add_asset()") from None


def add_asset(a: Asset, *, replace: bool = False) -> None:
    """List another model or dataset (e.g. your own checkpoint) so ``gyeol fetch`` and provenance records know it."""
    if a.name in ASSETS and not replace:
        raise ValueError(f"{a.name!r} is already listed")
    ASSETS[a.name] = a


def describe(name: str) -> dict:
    """Provenance record for checkpoints and model cards: the listed fields, or just the name if it is not listed."""
    a = ASSETS.get(name)
    return asdict(a) if a is not None else {"name": name, "kind": "unlisted", "license": "unknown (not in gyeol's asset list)"}


__all__ = ["ASSETS", "Asset", "CODE", "DATASET", "WEIGHTS", "add_asset", "asset", "describe"]
